# **Primary Key each dataset**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path = '/content/drive/MyDrive/Dataset_Final_Project/'

df_Cust = pd.read_excel(f'{path}Customers.xlsx')
df_Ord = pd.read_excel(f'{path}Orders.xlsx')
df_ProdCat = pd.read_excel(f'{path}ProductCategory.xlsx')
df_Prod = pd.read_excel(f'{path}Products.xlsx')

print('==Customers==')
display(df_Cust.head())
print('\n==Order==')
display(df_Ord.head())
print('\n==Product_Category==')
display(df_ProdCat.head())
print('\n==Product==')
display(df_Prod.head())

==Customers==

,CustomerID,FirstName,LastName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCity,CustomerState,CustomerZip
0,1,Grazia,Rasmus,grasmusas@i2i.jp#mailto:grasmusas@i2i.jp#,(202) 577-2595,628 Buhler Junction,Washington,District of Columbia,20029
1,2,Bunny,Trevan,btrevanmj@wordpress.org#mailto:btrevanmj@wordp...,917-903-2827,52 Cascade Drive,Jamaica,New York,11436
2,3,Tracie,Grayston,tgrayston7k@pagesperso-orange.fr#mailto:tgrays...,404-868-2391,672 Comanche Way,Atlanta,Georgia,30343
3,4,Amerigo,Garrelts,agarrelts6e@oaic.gov.au#mailto:agarrelts6e@oai...,415-190-3290,8252 Village Green Hill,San Francisco,California,94177
4,5,Shea,Stronghill,sstronghillc1@google.nl#mailto:sstronghillc1@g...,432-775-7828,542 3rd Point,Midland,Texas,79705

==Order==

   OrderID       Date  CustomerID ProdNumber  Quantity
0        1 2020-01-01        1866      EB514         2
1        2 2020-01-01        1567      RS706         3
2        3 2020-01-01        2064      TV804         6
3        4 2020-01-01         287      DK203         1
4        5 2020-01-01         422      EB517         5

==Product_Category==

   CategoryID CategoryName CategoryAbbreviation
0           1   Blueprints                   BP
1           2   Drone Kits                   DK
2           3       Drones                   DS
3           4       eBooks                   EB
4           5   Robot Kits                   RK

==Product==

  ProdNumber                       ProdName  Category  Price
0      BP101       All Eyes Drone Blueprint         1   9.99
1      BP102        Bsquare Robot Blueprint         1   8.99
2      BP104            Cat Robot Blueprint         1   4.99
3      BP105  Creature Robot Arms Blueprint         1  12.00
4      BP106     Hexacopter Drone Blueprint         1   8.99

In [ ]:
print('==Customers==')
df_Cust.info()
print('\n==Order==')
df_Ord.info()
print('\n==Product_Category==')
df_ProdCat.info()
print('\n==Product==')
df_Prod.info()

==Customers==
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2123 entries, 0 to 2122
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       2123 non-null   int64
 1   FirstName        2123 non-null   object
 2   LastName         2123 non-null   object
 3   CustomerEmail    2123 non-null   object
 4   CustomerPhone    2123 non-null   object
 5   CustomerAddress  2123 non-null   object
 6   CustomerCity     2123 non-null   object
 7   CustomerState    2123 non-null   object
 8   CustomerZip      2123 non-null   int64
dtypes: int64(2), object(7)
memory usage: 149.4+ KB

==Order==
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3339 entries, 0 to 3338
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     3339 non-null   int64
 1   Date        3339 non-null   datetime64[ns]
 2   CustomerID  3339 non-null   int64
 3   ProdNumber  3339 non-null   object
 4   Quantity    3339 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 130.6+ KB

==Product_Category==
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CategoryID            7 non-null      int64
 1   CategoryName          7 non-null      object
 2   CategoryAbbreviation  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

==Product==
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ProdNumber  70 non-null     object
 1   ProdName    70 non-null     object
 2   Category    70 non-null     int64
 3   Price       70 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 2.3+ KB

In [ ]:
checks = {
    'Customers': (df_Cust, 'CustomerID'),
    'Orders': (df_Ord, 'OrderID'),
    'ProductCategory': (df_ProdCat, 'CategoryID'),
    'Products': (df_Prod, 'ProdNumber')
}

for table_name, (df, col) in checks.items():
    total_rows = len(df)
    unique_values = df[col].nunique()
    null_values = df[col].isna().sum()
    is_valid_pk = (total_rows == unique_values) and (null_values == 0)

    print(f'Tabel: {table_name}')
    print(f'  Kolom PK      : {col}')
    print(f'  Total baris   : {total_rows}')
    print(f'  Nilai unik    : {unique_values}')
    print(f'  Nilai kosong  : {null_values}')
    print(f'  Valid sebagai Primary Key? : {is_valid_pk}')
    print('-' * 40)

Tabel: Customers
  Kolom PK      : CustomerID
  Total baris   : 2123
  Nilai unik    : 2123
  Nilai kosong  : 0
  Valid sebagai Primary Key? : True
----------------------------------------
Tabel: Orders
  Kolom PK      : OrderID
  Total baris   : 3339
  Nilai unik    : 3339
  Nilai kosong  : 0
  Valid sebagai Primary Key? : True
----------------------------------------
Tabel: ProductCategory
  Kolom PK      : CategoryID
  Total baris   : 7
  Nilai unik    : 7
  Nilai kosong  : 0
  Valid sebagai Primary Key? : True
----------------------------------------
Tabel: Products
  Kolom PK      : ProdNumber
  Total baris   : 70
  Nilai unik    : 70
  Nilai kosong  : 0
  Valid sebagai Primary Key? : True
----------------------------------------

# **Relationship antar Dataset**

| Origin Table | Column (FK) | Objective Table | Column (PK) | Relationship Type
|-------------|-------------|-------------|-------------|-------------|
| Orders | CustomersID | Customers | CustomersID | One-to-Many (1-M) |
| Orders | ProdNumber | Products | Prodnumber | Many-to-one (M-1) |
| Products | Category | Product Category | CategoryID | Many-to-One (M-1) |

# **Creating New Master Dataset Based on Primary Dataset**

In [ ]:
# Join Orders with Customers

df_Ord_Cust = df_Ord.merge(df_Cust, on='CustomerID', how='inner')

df_Ord_Cust.info()
print('\n')
display(df_Ord_Cust.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3339 entries, 0 to 3338
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          3339 non-null   int64
 1   Date             3339 non-null   datetime64[ns]
 2   CustomerID       3339 non-null   int64
 3   ProdNumber       3339 non-null   object
 4   Quantity         3339 non-null   int64
 5   FirstName        3339 non-null   object
 6   LastName         3339 non-null   object
 7   CustomerEmail    3339 non-null   object
 8   CustomerPhone    3339 non-null   object
 9   CustomerAddress  3339 non-null   object
 10  CustomerCity     3339 non-null   object
 11  CustomerState    3339 non-null   object
 12  CustomerZip      3339 non-null   int64
dtypes: datetime64[ns](1), int64(4), object(8)
memory usage: 339.2+ KB

,OrderID,Date,CustomerID,ProdNumber,Quantity,FirstName,LastName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCity,CustomerState,CustomerZip
0,1,2020-01-01,1866,EB514,2,Farrand,Vasler,fvaslerqt@comsenz.com#mailto:fvaslerqt@comsenz...,601-786-0195,134 Melrose Pass,Jackson,Mississippi,39216
1,2,2020-01-01,1567,RS706,3,Terencio,McKern,tmckernot@tinyurl.com#mailto:tmckernot@tinyurl...,832-987-8363,26 Muir Lane,Katy,Texas,77493
2,3,2020-01-01,2064,TV804,6,Geordie,Stiggers,gstiggersdd@eventbrite.com#mailto:gstiggersdd@...,727-777-8163,11106 Cordelia Plaza,Saint Petersburg,Florida,33737
3,4,2020-01-01,287,DK203,1,Elna,De Angelo,edew@nba.com#mailto:edew@nba.com#,808-945-4067,78 Shasta Park,Honolulu,Hawaii,96820
4,5,2020-01-01,422,EB517,5,Lucita,Lesper,llespercx@com.com#mailto:llespercx@com.com#,515-193-2721,393 Holmberg Center,Des Moines,Iowa,50315

In [ ]:
# Join df_Ord_Cust with Products

df_Ord_Cust_Prod = df_Ord_Cust.merge(df_Prod, on='ProdNumber', how='inner')

df_Ord_Cust_Prod.info()
print('\n')
display(df_Ord_Cust_Prod.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3339 entries, 0 to 3338
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          3339 non-null   int64
 1   Date             3339 non-null   datetime64[ns]
 2   CustomerID       3339 non-null   int64
 3   ProdNumber       3339 non-null   object
 4   Quantity         3339 non-null   int64
 5   FirstName        3339 non-null   object
 6   LastName         3339 non-null   object
 7   CustomerEmail    3339 non-null   object
 8   CustomerPhone    3339 non-null   object
 9   CustomerAddress  3339 non-null   object
 10  CustomerCity     3339 non-null   object
 11  CustomerState    3339 non-null   object
 12  CustomerZip      3339 non-null   int64
 13  ProdName         3339 non-null   object
 14  Category         3339 non-null   int64
 15  Price            3339 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(9)
memory usage: 417.5+ KB

,OrderID,Date,CustomerID,ProdNumber,Quantity,FirstName,LastName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCity,CustomerState,CustomerZip,ProdName,Category,Price
0,1,2020-01-01,1866,EB514,2,Farrand,Vasler,fvaslerqt@comsenz.com#mailto:fvaslerqt@comsenz...,601-786-0195,134 Melrose Pass,Jackson,Mississippi,39216,Polar Robots,4,23.99
1,2,2020-01-01,1567,RS706,3,Terencio,McKern,tmckernot@tinyurl.com#mailto:tmckernot@tinyurl...,832-987-8363,26 Muir Lane,Katy,Texas,77493,RWW-75 Robot,6,883.00
2,3,2020-01-01,2064,TV804,6,Geordie,Stiggers,gstiggersdd@eventbrite.com#mailto:gstiggersdd@...,727-777-8163,11106 Cordelia Plaza,Saint Petersburg,Florida,33737,Drone Video Techniques,7,37.99
3,4,2020-01-01,287,DK203,1,Elna,De Angelo,edew@nba.com#mailto:edew@nba.com#,808-945-4067,78 Shasta Park,Honolulu,Hawaii,96820,BYOD-220,2,69.00
4,5,2020-01-01,422,EB517,5,Lucita,Lesper,llespercx@com.com#mailto:llespercx@com.com#,515-193-2721,393 Holmberg Center,Des Moines,Iowa,50315,SCARA Robots,4,19.50

In [ ]:
# Join df_Ord_Cust_Prod with Product Category

df_Master = df_Ord_Cust_Prod.merge(df_ProdCat, left_on='Category', right_on='CategoryID', how='inner')

df_Master.info()
print('\n')
display(df_Master.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3339 entries, 0 to 3338
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   OrderID               3339 non-null   int64
 1   Date                  3339 non-null   datetime64[ns]
 2   CustomerID            3339 non-null   int64
 3   ProdNumber            3339 non-null   object
 4   Quantity              3339 non-null   int64
 5   FirstName             3339 non-null   object
 6   LastName              3339 non-null   object
 7   CustomerEmail         3339 non-null   object
 8   CustomerPhone         3339 non-null   object
 9   CustomerAddress       3339 non-null   object
 10  CustomerCity          3339 non-null   object
 11  CustomerState         3339 non-null   object
 12  CustomerZip           3339 non-null   int64
 13  ProdName              3339 non-null   object
 14  Category              3339 non-null   int64
 15  Price                 3339 non-null   float64
 16  CategoryID            3339 non-null   int64
 17  CategoryName          3339 non-null   object
 18  CategoryAbbreviation  3339 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(6), object(11)
memory usage: 495.8+ KB

,OrderID,Date,CustomerID,ProdNumber,Quantity,FirstName,LastName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCity,CustomerState,CustomerZip,ProdName,Category,Price,CategoryID,CategoryName,CategoryAbbreviation
0,1,2020-01-01,1866,EB514,2,Farrand,Vasler,fvaslerqt@comsenz.com#mailto:fvaslerqt@comsenz...,601-786-0195,134 Melrose Pass,Jackson,Mississippi,39216,Polar Robots,4,23.99,4,eBooks,EB
1,2,2020-01-01,1567,RS706,3,Terencio,McKern,tmckernot@tinyurl.com#mailto:tmckernot@tinyurl...,832-987-8363,26 Muir Lane,Katy,Texas,77493,RWW-75 Robot,6,883.00,6,Robots,RS
2,3,2020-01-01,2064,TV804,6,Geordie,Stiggers,gstiggersdd@eventbrite.com#mailto:gstiggersdd@...,727-777-8163,11106 Cordelia Plaza,Saint Petersburg,Florida,33737,Drone Video Techniques,7,37.99,7,Training Videos,TV
3,4,2020-01-01,287,DK203,1,Elna,De Angelo,edew@nba.com#mailto:edew@nba.com#,808-945-4067,78 Shasta Park,Honolulu,Hawaii,96820,BYOD-220,2,69.00,2,Drone Kits,DK
4,5,2020-01-01,422,EB517,5,Lucita,Lesper,llespercx@com.com#mailto:llespercx@com.com#,515-193-2721,393 Holmberg Center,Des Moines,Iowa,50315,SCARA Robots,4,19.50,4,eBooks,EB

In [ ]:
# SUM Sales_total
df_Master['Sales_total'] = df_Master['Quantity'] * df_Master['Price']

# Rename 8 Columns
df_Final = df_Master[[
    'CustomerEmail',
    'CustomerCity',
    'Date',
    'Quantity',
    'ProdName',
    'Price',
    'CategoryName',
    'Sales_total'
]].copy()

df_Final.columns = [
    'cust_email',
    'cust_city',
    'order_date',
    'order_qty',
    'product_name',
    'product_price',
    'category_name',
    'total_sales'
]

# ASCED by Order_date
df_Final = df_Final.sort_values(by=['order_date', 'order_qty'], ascending=True).reset_index(drop=True)

print('Master Table Final')
df_Final.info()
print('\n')
display(df_Final.head(10))
print(f'\nTotal rows: {len(df_Final)}')

Master Table Final
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3339 entries, 0 to 3338
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cust_email     3339 non-null   object
 1   cust_city      3339 non-null   object
 2   order_date     3339 non-null   datetime64[ns]
 3   order_qty      3339 non-null   int64
 4   product_name   3339 non-null   object
 5   product_price  3339 non-null   float64
 6   category_name  3339 non-null   object
 7   total_sales    3339 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 208.8+ KB

,cust_email,cust_city,order_date,order_qty,product_name,product_price,category_name,total_sales
0,edew@nba.com#mailto:edew@nba.com#,Honolulu,2020-01-01,1,BYOD-220,69.00,Drone Kits,69.00
1,fvaslerqt@comsenz.com#mailto:fvaslerqt@comsenz...,Jackson,2020-01-01,2,Polar Robots,23.99,eBooks,47.98
2,tmckernot@tinyurl.com#mailto:tmckernot@tinyurl...,Katy,2020-01-01,3,RWW-75 Robot,883.00,Robots,2649.00
3,llespercx@com.com#mailto:llespercx@com.com#,Des Moines,2020-01-01,5,SCARA Robots,19.50,eBooks,97.50
4,lfromonte9@de.vu#mailto:lfromonte9@de.vu#,Birmingham,2020-01-01,5,Spherical Robots,16.75,eBooks,83.75
5,gstiggersdd@eventbrite.com#mailto:gstiggersdd@...,Saint Petersburg,2020-01-01,6,Drone Video Techniques,37.99,Training Videos,227.94
6,ksteershp@ameblo.jp#mailto:ksteershp@ameblo.jp#,San Diego,2020-01-02,1,Understanding Automation,44.95,Training Videos,44.95
7,aguiongo@behance.net#mailto:aguiongo@behance.net#,Houston,2020-01-02,2,BYOR-2640S,189.00,Robot Kits,378.00
8,lgatenbyel@quantcast.com#mailto:lgatenbyel@qua...,Des Moines,2020-01-02,2,Drone Video Techniques,37.99,Training Videos,75.98
9,jcolthurstgu@cbsnews.com#mailto:jcolthurstgu@c...,Sacramento,2020-01-02,2,DTE-QFN20 Drone,250.00,Drones,500.00

Total rows: 3339

In [ ]:
df_Final.to_csv('Master_Sales_Data.csv', index=False)